---
swagger: "2.0"
info:
  version: "2017-08-09T02:06:01Z"
  title: "dicer"
host: "79v1x086aj.execute-api.us-west-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /roll/{dice}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "dice"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:us-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-1:314749681433:function:dice-roller-stack*/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
